# Generated by Django 2.2.6 on 2021-03-22 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210227_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Выберите группу из перечисленных, либо пропустите поле', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Group', verbose_name='Выберите группу'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст', verbose_name='Текст поста'),
        ),
    ]
